### ISSUE TITLE
Skeleton-based signing?

### ISSUE THREAD

**Issue by andrewwhitehead** [w3c-ccg/ldp-bbs2020#40]
Rather than signing each statement of the N-quads, I'm interested in whether the whole 'shape' of the original document could be signed, with optionally-revealed values contained in subsequent messages. For example, taking the following document:

```json
{
    "@context": [ "http://myschema.org/" ],
    "memberId": "A00001",
    "memberAge": 30,
    "state": "Active",
}
```

The statements might be normalized as follows:

```
_:c14n0 <http://myschema.org/memberId> "A00001" .
_:c14n0 <http://myschema.org/memberAge> "30"^^<http://www.w3.org/2001/XMLSchema#integer> .
_:c14n0 <http://myschema.org/state> "Active" .
```

This entire block could be signed for a simple credential with all the statements being required, using only a single message. Alternatively, one or more fields might be optionally revealed by the holder. This example uses a 'meta-syntax' but something natively compatible with JSON-LD might be possible:

**message `0`**
```
_:c14n0 <http://myschema.org/memberId> ${1}.
_:c14n0 <http://myschema.org/memberAge> ${2}^^<http://www.w3.org/2001/XMLSchema#integer> .
_:c14n0 <http://myschema.org/state> "Active" .
```

**message `1`**
```
A00001
```

**message `2`**
```
30
```

Benefits of this approach:

- There is no special handling of 'required revealed' indexes. The issuer can easily inspect which information must always be shared.
- There is a common representation whether optionally-revealed statements are used or not.
- Other message canonicalization methods are possible, based on the declared RDF type of a property value. This could help facilitate predicate proofs.

Downsides:

- The parsing of the 'skeleton' message would need to be clearly defined and audited for security.
- Additional information is necessarily revealed in that entire statements cannot be completely omitted from a proof, only their property values. (This could also be a benefit for the issuer in terms of preventing misrepresentation of the signed data.)

Any issues with blank node identifiers would seem to require the same workarounds as proposed earlier.

**Comment by kdenhartog** [comment]
Just checking to make sure I understand the proposal correctly first. Is the intent to do both the separation of the value (`30`) in the N-Quad for selective disclosure and also to be able to bind N-Quad statements within the same node to each others (e.g. the memberId, memberAge, and State property N-Quads are all combined into a single message?

**Comment by andrewwhitehead** [comment]
@kdenhartog Basically, all the N-Quad statements resulting from the normalized document would be combined in message 0, while the object of those statements might be deferred to a later message if it's optionally revealed.

**Comment by kdenhartog** [comment]
Ok thanks. I'll have to think about the implications on revealing the document structure a bit before I write up a response. On first gut reaction I think this could impact the privacy, but I want to convince myself by thinking through a few use cases to see if it's desirable or not.

**Comment by tplooker** [comment]
@andrewwhitehead interesting concept, how would I if I signed all messages in the first one selectively reveal, wouldn't revealing this message reveal all the data?

**Comment by andrewwhitehead** [comment]
@tplooker The first message would use placeholders for the selectively revealed messages. Those placeholders would refer to subsequent messages (by their index). I think there would need to be a basic validation rule that all {1..N} messages must be referenced in the zeroth message, and can only be referenced once.

**Comment by tplooker** [comment]
@andrewwhitehead ok cool understood, could you explain why we would need to sign a skeleton like this what are the benefits?

**Comment by andrewwhitehead** [comment]
So the main benefits as I see it..

- Required-revealed indexes are not a thing – if an attribute is required to be revealed (such as revocation info), then it would just be included in the first (zeroth) message. It also makes things quite simple in cases where there are no optionally-revealed properties, in that the issuer just converts the document to N-quads and signs the result in one message.

- In cases where the objects of statements are deferred to subsequent messages, each claim is its own message, so there is an opportunity to use alternative encodings/canonicalizations rather than simply hashing the value. This would be determined based on the RDF type of the attribute (I would suggest introducing new RDF types in that case rather than defining special behaviour for xsd:integer for example). I believe this would help facilitate predicate proofs.

- The third issue is the potential misrepresentation of an issued document by intentionally leaving out signed statements. This might be partly mitigated by required-revealed indexes but as a verifier I think I'd prefer this approach, which makes it clear exactly what is being left out. As an example take the following document:

```jsonld
{
    "@context": [ "http://schema.org/" ],
    "type": "Person",
    "name": "Bob",
    "children": [
    	{"name": "Mary"},
	{"name": "Mark"}
    ]
}
```

Normalized into:

```
_:b0 <http://schema.org/children> _:b1 .
_:b0 <http://schema.org/children> _:b2 .
_:b0 <http://schema.org/name> "Bob" .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
_:b1 <http://schema.org/name> "Mary" .
_:b2 <http://schema.org/name> "Mark" .
```

If each of these statements is signed independently and not required to be revealed, I believe the holder can successfully present the following document which suggests they only have one child (poor Mark):

```jsonld
{
    "@context": [ "http://schema.org/" ],
    "type": "Person",
    "name": "Bob",
    "children": [
    	{"name": "Mary"}
    ]
}
```

As for whether this forces the holder to reveal more than intended, I believe that can generally be mitigated by issuing separate but linked credentials for sensitive information. Although it would be interesting to see some more practical examples.

**Comment by andrewwhitehead** [comment]
Closing as out of scope for this suite
