### ISSUE TITLE
Differing statement digest algorithms?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/ldp-bbs2020#53]
Is there a reason The BBS+ Signature Suite 2020 and The BBS+ Signature Proof Suite 2020 have differing statement digest algos? I also don't see the statement digest algo being used in the "Create Derive Proof Data Algorithm" at any point?

**Comment by tplooker** [comment]
Thanks @brianorwhatever addressed in #54

**Comment by brianorwhatever** [comment]
out of curiosity why was this algorithm picked?

**Comment by brianorwhatever** [comment]
also, how does the algorithm get used in the proof suite?

**Comment by tplooker** [comment]
@mikelodder7 can confirm why the current algorithm was chosen. As to how it is used, every message/statement that is signed has to be digested/hash first this algorithm defines how this is performed.

**Comment by mikelodder7** [comment]
Blake2b was chosen because it’s flexible in its output length, faster than sha2 and sha3, is widely used, is optimized for 64  bit architectures, and blake3 was close to being released at the time and is out now.

**Comment by mikelodder7** [comment]
The hash algorithm is used to create the schnorr proof challenge hash
